### ISSUE TITLE
Analizar e implementar el flujo para el versonamiento de los planes y los estados de los planes o proyectos

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planes_crud#32]
Se debe realizar el análisis  como implementar el flujo de versonamiento para los planes, esto para poder tener una trazabilidad de la modificaciones de los planes por observaciones, también se debe buscar la solución  para el manejo de los estados de los planes, esto para saber los cambios de estado de los planes y poder una trazabilidad al seguimiento de los planes, la issue debe cumplir con los siguientes requerimientos:

- [x] Analizar e implementar el flujo de versonamiento para los planes ( ajustes de modelo, grafico en la carpeta drive y modelos y controladores) 
- [x] Analizar e implementar el flujo de estados para los planes ( ajustes de modelo, grafico en la carpeta drive y modelos y controladores)

**Comment by ndmc98** [comment]
Se da inicio a la issue el 20/09/2021

**Comment by ndmc98** [comment]
Se ajusta el modelo y se carga el gráfico en Drive. Tras validación por parte del líder y el conocimiento del equipo, se ajusta el modelo y los controladores para el flujo de versionamiento y estados.

**Comment by ndmc98** [comment]
Tras validación y pruebas en local de las modificaciones, se genera el Pull Request.

**Comment by ndmc98** [comment]
Nuevo endpoint: estado-plan
Nuevos campos en Plan: estado_plan_id y padre_plan_id

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
