### ISSUE TITLE
Creación de función GET con filtro para consulta de planes particulares 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planes_crud#37]
Se debe desarrollar una función de consulta para planes asignado o particulares, para esto este método debe tener los siguientes parámetros de entrada: tipo de plan, vigencia y unidad, y debe devolver el plan completo encontrado, la issue debe cumplir con los siguientes requerimientos:

- [x] Crear la función con los parámetros indicados y el responde mencionado
- [x] Ceñirse a los lineamientos en cuanto al cuerpo de la respuesta

**Comment by ndmc98** [comment]
Se da inicio a la issue el 29/09/2021

**Comment by ndmc98** [comment]
Se crea el modulo _filters_ con la estructura necesaria para la definición de los diferentes filtros a emplear desde la api crud:

- query - Filter. e.g. col1:v1,col2:v2 … _Filtro de consulta campo:valor (selección)_
- fields - Fields returned. e.g. col1,col2 … _Filtro de consulta por campo (proyección)_
- sortby - Sorted-by fields. e.g. col1,col2 … _Filtro de ordenamiento_
- order - Order corresponding to each sortby field, if single value, apply to all sortby fields. e.g. desc,asc … 
- limit - Limit the size of result set. Must be an integer
- offset - Start position of result set. Must be an integer
- populate - show subqueries. Must be a boolean

**Comment by ndmc98** [comment]
Se utiliza el servicio de _filters_ en la función GET del modulo PLAN. 

_El servicio filters es replicable a cualquier modulo en la función GET_

**Comment by ndmc98** [comment]
Se genera el Pull Request con los cambios mencionados. Por solicitud el último cambio incluye los filters en los controllers y services de todos los modulos.

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
